### ISSUE TITLE
Minimum time before clicking next while searching resets itself to zero

### ISSUE THREAD

**Issue by hlygrail** [maxcom99/brokenbot-support#10]
Possibly due to [https://github.com/maxcom99/brokenbot-support/issues/8](https://github.com/maxcom99/brokenbot-support/issues/8) (BB not exiting cleanly), the setting for number of seconds to wait before clicking Next during search **resets itself to zero** quite often.

**Comment by maxcom99** [comment]
Resolved in coc bot brokenbot v5 - more info at [Clash of Clans Bot](https://brokenbot.org)
