### ISSUE TITLE
Error reading troops and fatal error one or more threads.

### ISSUE THREAD

**Issue by Dobbo714** [maxcom99/brokenbot-support#12]
Was working fine previously all of a sudden cannot read troops, claims to be unable to train minions and after 3 attempts has a fatal error on one or more threads, i have tried all variants of capture mode with no luck, any help would be appreciate

side issue: Bot fails to locate TH and heroes automatically and after i set them myself
 bot still sometimes misses them and clicks on walls etc 

![capture](https://cloud.githubusercontent.com/assets/24642583/21299163/195a61b2-c5ed-11e6-8660-805310f030b5.PNG)

**Comment by maxcom99** [comment]
Resolved in coc bot brokenbot v5 - more info at [Clash of Clans Bot](https://brokenbot.org)
