### ISSUE TITLE
Donation Loop v4.7.0

### ISSUE THREAD

**Issue by CybrZr00** [maxcom99/brokenbot-support#15]
Bot gets stuck in doation loop, I noticed that on first cycle it donated only partial numbers of troops per person (4 instead of 8), and susequent loops, no doations were given despite there being room.  Full log added as zip.

[20161223-163741.zip](https://github.com/maxcom99/brokenbot-support/files/671183/20161223-163741.zip)

**Comment by maxcom99** [comment]
Closing as resolved in 4.7.4
