### ISSUE TITLE
Spells not deploying

### ISSUE THREAD

**Issue by pidgetfu** [maxcom99/brokenbot-support#18]
After days of running bot stopped deploying spells.  Cleared BB setting changed bot speed to slow no luck.

![untitled1](https://cloud.githubusercontent.com/assets/24762918/21471206/ac12c9fc-ca77-11e6-8bd1-7c1b42eb502c.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/24762918/21471207/ac1ccbf0-ca77-11e6-940f-47934fe48a0c.jpg)
![untitled3](https://cloud.githubusercontent.com/assets/24762918/21471208/ac1d06a6-ca77-11e6-8485-d8788817aa5c.jpg)

**Comment by pidgetfu** [comment]
Rebooting Clearing Settings again and losing CC troops fixed this issue.  I will try with cc troops again after sleep and update thread,

**Comment by pidgetfu** [comment]
Confirmed it was the cc troops.

**Comment by maxcom99** [comment]
Resolved in coc bot brokenbot v5 - more info at [Clash of Clans Bot](https://brokenbot.org)
