### ISSUE TITLE
Spells and Certain Troops/Spells Not Deploying

### ISSUE THREAD

**Issue by sakue** [maxcom99/brokenbot-support#19]
Using MEmu, and I've used two different strategies now that both have deploys that don't occur. In the first strategy (Seb's TH9 DE), neither the rage or heal spells deployed. In the other strategy (VIPINVITE's TH9 DE), the spells, healers, and wizards did not deploy.

**Comment by chongki** [comment]
any updates? I've tried clearing CC and resetting setting but still no luck.

**Comment by sakue** [comment]
Same for me. Cant seem to figure it out.

**Comment by iotola** [comment]
Yes I am also experiencing this issue. It was working, then stopped, possibly due to cc troops.
I have since removed the cc troops and reset all settings, but it still does not work. 
Just cant work out how to resolve it.

**Comment by iotola** [comment]
Spells started working while I had hero active but then stopped again once the hero went back to upgrading. [I have noticed that when you have a hero the spells and troops are more separated. Maybe this effects the deployment?]

**Comment by sakue** [comment]
That might have something to do with it. Both my heroes are upgrading currently. Can't really bot right now because troops get left unused. CC is empty. No spells cooked. And setting all reset. No change.

**Comment by maxcom99** [comment]
@sakue can you try removing your heros from the building detection?

**Comment by sakue** [comment]
I will try that when I have a chance. Standby

**Comment by sakue** [comment]
@maxcom99 No change. Using the same strategy, I deleted the building location for both of my heroes. Ran the bot, and neither the wiz, healers, and rage spell were deployed.

**Comment by MrGr3G** [comment]
I'm having issues with lava hounds not deploying.. all other troops/spells/heroes are deploying fine...

**Comment by maxcom99** [comment]
Resolved in coc bot brokenbot v5 - more info at [Clash of Clans Bot](https://brokenbot.org)
