### ISSUE TITLE
Memu - Waiting For Unwanted Text

### ISSUE THREAD

**Issue by zevnda** [maxcom99/brokenbot-support#24]
https://brokenbot.org/forum/threads/unwanted-text.5964/

**Comment by JLimqueco** [comment]
I'm also getting the same warning when the bot is training a bunch of goblins, and when the count reaches "100 left". FWIW, I'm using the "dirtypny Goblin Milking" strategy.

![screen shot 2017-01-27 at 14 08 07 pm](https://cloud.githubusercontent.com/assets/9668935/22386110/31db73bc-e49b-11e6-831e-ffe73f9b517e.png)
