### ISSUE TITLE
4.7.2 - Inferno Towers Sometimes are not Reloaded

### ISSUE THREAD

**Issue by chris-will** [maxcom99/brokenbot-support#28]
I'm sure you guys know about this one. Just didn't see it listed here in the issues list. LMK if you need more details but this must be an image recognition issue. Not such a high priority issue I'm sure of it!

**Comment by hlygrail** [comment]
Ditto -- see this occasionally.  Not entirely sure it's a recognition issue, though... unfortunately I haven't been here to see when it didn't reload, I just notice now and then that it's been running for <hours> un-reloaded, which means it's semi-persistent.

**Comment by maxcom99** [comment]
Closing as resolved in 4.7.4
