### ISSUE TITLE
Does not detect buildings

### ISSUE THREAD

**Issue by AxEgo** [maxcom99/brokenbot-support#3]
When the bot is started from fresh, it cannot detect buildings. It detects them all at the left hand side by the chat tab.

When the bot goes into building edit mode, click "Clear All" and detect the buildings one by one and it [generally] detects them correctly.

**Comment by dls314** [comment]
@AxEgo 

Thank you for the issue. Do you have any forum links that are related? I'd like to link back to help folks who want to participate in both places.

**Comment by AxEgo** [comment]
https://forum.brokenbot.org/thread-5936-post-51260.html

**Comment by maxcom99** [comment]
Closing as resolved in 4.7.4
