### ISSUE TITLE
FIX:  Many configuration settings are not retained during upgrade

### ISSUE THREAD

**Issue by hlygrail** [maxcom99/brokenbot-support#34]
On every upgrade, BB seems to "forget" all of these settings, and they have to be re-set.

Advanced Tab
  Search
    > A hero becomes available (always ends up **unchecked** after upgrade)
    > A spell finishes brewing (always ends up **unchecked** after upgrade)
    > After searching XXX +/- YY bases (always ends up **unchecked** after upgrade)

  Speed
    General speed ((always reverts to "**middle**")
    Troop deploy delay (always reverts to "**a fast human**")
    How fast fingers move...  (always reverts to "**Quick**")
    ___ sec minimum time before clicking Next  (always reverts to **zero**)

  Dead Bases
    By % in collectors... the percentage ALWAYS reverts back to **25%** after upgrade.

There are probably others that get reset as well, but these are the ones I encounter each time (I guess because I don't run the defaults for these).

**Comment by maxcom99** [comment]
Resolved in coc bot brokenbot v5 - more info at [Clash of Clans Bot](https://brokenbot.org)
