### ISSUE TITLE
Spells Error Message

### ISSUE THREAD

**Issue by AxEgo** [maxcom99/brokenbot-support#6]
It's a small issue, but slightly annoying. BrokenBot displays "All requested spells do not fit because of previously cooked spells. Ignoring "Wait for Spells".

This happens when all spell slots are full even though the strategy does not cook spells, use spells or have "Wait for Spells" ticked.

![spells](https://cloud.githubusercontent.com/assets/24453278/21038937/9e886a18-bde2-11e6-82fa-f2da1c91c835.png)

**Comment by maxcom99** [comment]
Resolved in coc bot brokenbot v5 - more info at [Clash of Clans Bot](https://brokenbot.org)
