### ISSUE TITLE
GiBarch - First attack fine - next army doesn't get trained correctly.

### ISSUE THREAD

**Issue by subvhome** [maxcom99/brokenbot-support#7]
OS: Windows 10
BS: 10.0.4321 KitKat Rooted Offline Installer
or
Memu: Latest
BB: 4.6.1
Stradegy: CT83 [ALL TH] Simple Dead Base Collector Attach GiBArch

When I load the game, I make sure I am all zoomed out. It looks like the initial tasks are done, collecting resources, checking traps, xbows... It then goes to create my army. Seems like it does this correctly.

The first attack seems fine. all troops deploy.. But when back to the army base... I get error reading number of troops in overview. And following attacks the army composition is all off.

My queen never gets deployed

Original Thread: http://forum.brokenbot.org/thread-5971.html

**Comment by maxcom99** [comment]
Resolved in coc bot brokenbot v5 - more info at [Clash of Clans Bot](https://brokenbot.org)
