### ISSUE TITLE
Brokenbot doesn't exit cleanly - leftover process(es), BB jumps to 100% CPU

### ISSUE THREAD

**Issue by hlygrail** [maxcom99/brokenbot-support#8]
There appears to only be one way to exit BrokenBot -- the big X at the top right of the window.  95% of the time, when you click the X, the BB window vanishes, but BrokenBot and its two associated Awesomium processes are still around.  It isn't obvious that it's still running, and another BB process can easily be started.

Worse, BrokenBot sits around and absorbs close to 100% CPU until it's force-closed via Task Manager. AND it slowly eats memory, too, while it's hiding away in undead-land.

Both of these issues need to be resolved.

**Comment by Dobbo714** [comment]
agreed
feel like i need an entire other rig because BB chews away at it lol

**Comment by maxcom99** [comment]
Resolved in coc bot brokenbot v5 - more info at [Clash of Clans Bot](https://brokenbot.org)
