### ISSUE TITLE
BrokenBot speed settings need more granularity

### ISSUE THREAD

**Issue by hlygrail** [maxcom99/brokenbot-support#9]
As of 4.6.x, BrokenBot has three speed settings:

- "General speed of the bot"  (adjustable from fast/middle/slow)
- "Delay between troops being deployed" (adjustable in 5 notches from banned to very slow)
- "How fast do your fingers move around the screen"  (adjustable in 5 notches from fast to crawling)

It seems that the time spent analyzing bases is controlled by the "general speed" setting.  Clicking to build the next army seems to be controlled by this setting as well.  Most modern PCs can easily handle the "Fast" general speed, but when setting attack strategies seem to fail because these two are linked together.

Separating these into more discrete settings will allow users to appropriately configure for their specific needs -- most often, that they want to train armies very quickly, but allow the app to "thoughtfully" analyze the bases during attacks to make sure it's hitting the right bases.  It will also prevent "bugs" being opened for non-specific issues and allow users to do their own testing to isolate problems before throwing up the red flag to the dev team (reduces noise for you guys!).

Suggested knobs might be something like this... and maybe the stuff in parentheses is a hover-over help):

- General Speed  (controls speed of building troops/spells, general clicking of/between menus, )
- Analysis Speed (controls how quickly BB looks at bases during attack -- purposely separate from others)
- Troop Delay (controls how quickly troops are **deployed** during attacks; also controls **donation** speed)
- Human-like Speed (controls how fast BB clicks between different areas of the screen)

**Comment by maxcom99** [comment]
Resolved in coc bot brokenbot v5 - more info at [Clash of Clans Bot](https://brokenbot.org)
